### PR TITLE
[DERCBOT-846] Rename LLM Orchestrator to Gen AI Orchestrator

### PR DESCRIPTION
**Pull request by assouktim**

### CODE REVIEW

**Review by Benvii — DISMISSED** [review]
LGTM

**Review by Benvii — APPROVED** [review]
After rebased from feature/rag/develop

**Comment by Benvii** [comment]
I'm working on it there is still work to do so that everything compile correctly with feature/rag/develop latest gen-ai packages.

**Review by Benvii — CHANGES_REQUESTED** [review]
Missing renaming of the folder : `llm-orchestrator-server` and file `docker-compose-llm-orchestrator.yml`

And other stuff I'm working on it currently.

**Comment by Benvii** [comment]
Still work to do :
- adapt DockerFile for Gen Ai orchestrator (package and copy folder name)
- use gunicorn inside

**Comment by assouktim** [comment]
It's done

**Pull request merged**
